## Decision Tree Classifier

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score


# Import Dataset
df = pd.read_csv('attrition_data_clean.csv')
X = df.drop('Attrition', axis=1) 
y = df['Attrition']  

# Split Train and Test Sets
splitter = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=123)
for train_index, test_index in splitter.split(X, y):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

# Separate features and target variables in training and test sets
X_train = strat_train_set.drop('Attrition', axis=1)
y_train = strat_train_set['Attrition']
X_test = strat_test_set.drop('Attrition', axis=1)
y_test = strat_test_set['Attrition']

'''
# Verify the splits
print("Training set:")
print(strat_train_set.head())

print("\nTest set:")
print(strat_test_set.head())
'''

# Train the Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=123)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print results
print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Confusion Matrix:
[[212  35]
 [ 32  15]]

Accuracy: 0.7721088435374149
F1 Score: 0.7749367284234961
Precision: 0.7779134604661536
Recall: 0.7721088435374149


## Random Forest Classifier

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score


# Import Dataset
df = pd.read_csv('attrition_data_clean.csv')
X = df.drop('Attrition', axis=1) 
y = df['Attrition']  

# Split Train and Test Sets
splitter = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=123)
for train_index, test_index in splitter.split(X, y):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

# Separate features and target variables in training and test sets
X_train = strat_train_set.drop('Attrition', axis=1)
y_train = strat_train_set['Attrition']
X_test = strat_test_set.drop('Attrition', axis=1)
y_test = strat_test_set['Attrition']

'''
# Verify the splits
print("Training set:")
print(strat_train_set.head())

print("\nTest set:")
print(strat_test_set.head())
'''

# Train the Random Forest Classifier
clf = RandomForestClassifier(random_state=123)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print results
print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Confusion Matrix:
[[244   3]
 [ 38   9]]

Accuracy: 0.8605442176870748
F1 Score: 0.8237935910002075
Precision: 0.8468241906691755
Recall: 0.8605442176870748


## K Nearest Neighbors Classifier

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.neighbors  import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score


# Import Dataset
df = pd.read_csv('attrition_data_clean.csv')
X = df.drop('Attrition', axis=1) 
y = df['Attrition']  

# Split Train and Test Sets
splitter = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=123)
for train_index, test_index in splitter.split(X, y):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

# Separate features and target variables in training and test sets
X_train = strat_train_set.drop('Attrition', axis=1)
y_train = strat_train_set['Attrition']
X_test = strat_test_set.drop('Attrition', axis=1)
y_test = strat_test_set['Attrition']

'''
# Verify the splits
print("Training set:")
print(strat_train_set.head())

print("\nTest set:")
print(strat_test_set.head())
'''

# Train the KNN Classifier
k=20
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print results
print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Confusion Matrix:
[[243   4]
 [ 46   1]]

Accuracy: 0.8299319727891157
F1 Score: 0.7679137671141935
Precision: 0.7383847656709743
Recall: 0.8299319727891157


## XGBoost Classifier

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
import xgboost as xgb
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score


# Import Dataset
df = pd.read_csv('attrition_data_clean.csv')
X = df.drop('Attrition', axis=1) 
y = df['Attrition']  

# Split Train and Test Sets
splitter = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=123)
for train_index, test_index in splitter.split(X, y):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

# Separate features and target variables in training and test sets
X_train = strat_train_set.drop('Attrition', axis=1)
y_train = strat_train_set['Attrition']
X_test = strat_test_set.drop('Attrition', axis=1)
y_test = strat_test_set['Attrition']

'''
# Verify the splits
print("Training set:")
print(strat_train_set.head())

print("\nTest set:")
print(strat_test_set.head())
'''

# Train the XGBoost Classifier
clf = xgb.XGBClassifier(random_state=123, use_label_encoder=False, eval_metric='mlogloss')
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print results
print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)



Confusion Matrix:
[[238   9]
 [ 32  15]]

Accuracy: 0.8605442176870748
F1 Score: 0.841058323784468
Precision: 0.8404793398841018
Recall: 0.8605442176870748


C:\Users\jarro\anaconda3\lib\site-packages\xgboost\core.py:158: UserWarning: [17:18:20] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


## Classifier Performance Summary

In [6]:
mod = pd.read_csv('classifierperformance.csv')
print(mod)

           Model  Accuracy  F1 Score  Precision    Recall
0  Decision Tree  0.772109  0.774937   0.777913  0.772109
1  Random Forest  0.860544  0.823794   0.846824  0.860544
2            KNN  0.829932  0.767914   0.738385  0.829932
3        XGBoost  0.860544  0.841058   0.840479  0.860544
